/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.htmlcolorporadnik;

import java.awt.Color;

/**
 *
 * @author emilk
 */
public class HtmlColorPoradnik extends javax.swing.JFrame {

    /**
     * Creates new form HtmlColorPoradnik
     */
    public HtmlColorPoradnik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelRed = new javax.swing.JLabel();
        jLabelGreen = new javax.swing.JLabel();
        jLabelBlue = new javax.swing.JLabel();
        jSliderRed = new javax.swing.JSlider();
        jSliderGreen = new javax.swing.JSlider();
        jSliderBlue = new javax.swing.JSlider();
        jLabelR = new javax.swing.JLabel();
        jLabelG = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelRValue = new javax.swing.JLabel();
        jLabelGValue = new javax.swing.JLabel();
        jLabelBValue = new javax.swing.JLabel();
        jLabelHTML = new javax.swing.JLabel();
        jTextFieldRGBValue = new javax.swing.JTextField();
        jPanelColor = new javax.swing.JPanel();
        jButtonCoral = new javax.swing.JButton();
        jButtonSalmon = new javax.swing.JButton();
        jButtonCyan = new javax.swing.JButton();
        jButtonBeige = new javax.swing.JButton();
        jButtonCoppery = new javax.swing.JButton();
        jButtonGamboge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("htmlColor");
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabelRed.setText("Red");

        jLabelGreen.setText("Green");

        jLabelBlue.setText("Blue");

        jSliderRed.setMajorTickSpacing(15);
        jSliderRed.setMaximum(255);
        jSliderRed.setMinorTickSpacing(1);
        jSliderRed.setPaintLabels(true);
        jSliderRed.setPaintTicks(true);
        jSliderRed.setSnapToTicks(true);
        jSliderRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRedStateChanged(evt);
            }
        });

        jSliderGreen.setMajorTickSpacing(15);
        jSliderGreen.setMaximum(225);
        jSliderGreen.setMinorTickSpacing(1);
        jSliderGreen.setPaintLabels(true);
        jSliderGreen.setPaintTicks(true);
        jSliderGreen.setSnapToTicks(true);
        jSliderGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderGreenStateChanged(evt);
            }
        });

        jSliderBlue.setMajorTickSpacing(15);
        jSliderBlue.setMaximum(255);
        jSliderBlue.setMinorTickSpacing(1);
        jSliderBlue.setPaintLabels(true);
        jSliderBlue.setPaintTicks(true);
        jSliderBlue.setSnapToTicks(true);
        jSliderBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBlueStateChanged(evt);
            }
        });

        jLabelR.setText("RED");

        jLabelG.setText("GREEN");

        jLabelB.setText("BLUE");

        jLabelRValue.setText(" ");

        jLabelGValue.setText(" ");

        jLabelBValue.setText(" ");

        jLabelHTML.setText("HTML");

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jButtonCoral.setText("Koralowy");
        jButtonCoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoralActionPerformed(evt);
            }
        });

        jButtonSalmon.setText("Łososiowy");
        jButtonSalmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalmonActionPerformed(evt);
            }
        });

        jButtonCyan.setText("Cyjan");
        jButtonCyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCyanActionPerformed(evt);
            }
        });

        jButtonBeige.setText("Beżowy");
        jButtonBeige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeigeActionPerformed(evt);
            }
        });

        jButtonCoppery.setText("Miedziany");
        jButtonCoppery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopperyActionPerformed(evt);
            }
        });

        jButtonGamboge.setText("Gumiguta");
        jButtonGamboge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGambogeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRed, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSliderRed, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(jSliderGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabelRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelGValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabelR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabelG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabelHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRGBValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCoral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalmon, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jButtonCyan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBeige, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCoppery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGamboge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRed)
                    .addComponent(jSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGreen)
                    .addComponent(jSliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelBlue)))
                .addGap(49, 49, 49)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR)
                    .addComponent(jLabelG)
                    .addComponent(jLabelB)
                    .addComponent(jLabelHTML)
                    .addComponent(jTextFieldRGBValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCoral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBValue)
                            .addComponent(jLabelGValue)
                            .addComponent(jLabelRValue))
                        .addGap(25, 25, 25)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonSalmon)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCyan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBeige)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCoppery)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGamboge)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRedStateChanged
        //pobieramy wartośći Sliderów i zapisujemy je Intem
        int red = jSliderRed.getValue();
        int green = jSliderGreen.getValue();
        int blue = jSliderBlue.getValue();
        
        setColor(red, green, blue);
        
        String redS = String.valueOf(red);
        jLabelRValue.setText(redS);
    }//GEN-LAST:event_jSliderRedStateChanged

    private void jSliderGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderGreenStateChanged
        int red = jSliderRed.getValue();
        int green = jSliderGreen.getValue();
        int blue = jSliderBlue.getValue();
        
        setColor(red, green, blue);
        
        String greenS = String.valueOf(green);
        jLabelGValue.setText(greenS);
    }//GEN-LAST:event_jSliderGreenStateChanged

    private void jSliderBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBlueStateChanged
        int red = jSliderRed.getValue();
        int green = jSliderGreen.getValue();
        int blue = jSliderBlue.getValue();
        
        setColor(red, green, blue);
        
        String blueS = String.valueOf(blue);
        jLabelBValue.setText(blueS);
    }//GEN-LAST:event_jSliderBlueStateChanged

    private void jButtonCoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoralActionPerformed
        setColor(255,127,80);
    }//GEN-LAST:event_jButtonCoralActionPerformed

    private void jButtonSalmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalmonActionPerformed
        setColor(255, 140, 105);
    }//GEN-LAST:event_jButtonSalmonActionPerformed

    private void jButtonCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCyanActionPerformed
        setColor(0,255,255);
    }//GEN-LAST:event_jButtonCyanActionPerformed

    private void jButtonBeigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeigeActionPerformed
        setColor(245,245,220);
    }//GEN-LAST:event_jButtonBeigeActionPerformed

    private void jButtonCopperyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopperyActionPerformed
        setColor(184,115,51);
    }//GEN-LAST:event_jButtonCopperyActionPerformed

    private void jButtonGambogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGambogeActionPerformed
        setColor(228,155,15);
    }//GEN-LAST:event_jButtonGambogeActionPerformed
    /**
     * Ustawiamy zmiane wartości Sliderów w razie zmiany 
     * koloru poprzez naciśnięcie w przycisk bądź wpisania w polu Wartości sześciennej
     */
    private void setColor(int red, int green, int blue) {
    jSliderRed.setValue(red);
    jSliderGreen.setValue(green);
    jSliderBlue.setValue(blue);

    jPanelColor.setBackground(new Color(red, green, blue));

    Color color = new Color(red, green, blue);
    String hex = "#" + Integer.toHexString(color.getRGB()).substring(2);
    jTextFieldRGBValue.setText(hex);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HtmlColorPoradnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HtmlColorPoradnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HtmlColorPoradnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HtmlColorPoradnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HtmlColorPoradnik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBeige;
    private javax.swing.JButton jButtonCoppery;
    private javax.swing.JButton jButtonCoral;
    private javax.swing.JButton jButtonCyan;
    private javax.swing.JButton jButtonGamboge;
    private javax.swing.JButton jButtonSalmon;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelBValue;
    private javax.swing.JLabel jLabelBlue;
    private javax.swing.JLabel jLabelG;
    private javax.swing.JLabel jLabelGValue;
    private javax.swing.JLabel jLabelGreen;
    private javax.swing.JLabel jLabelHTML;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelRValue;
    private javax.swing.JLabel jLabelRed;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JSlider jSliderBlue;
    private javax.swing.JSlider jSliderGreen;
    private javax.swing.JSlider jSliderRed;
    private javax.swing.JTextField jTextFieldRGBValue;
    // End of variables declaration//GEN-END:variables
}
